## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Description,Current Description
0,0,Cape Town,-33.9258,18.4232,48.11,100,0,1.14,ZA,2021-08-11 01:26:46,NaN,NaN
1,1,Butaritari,3.0707,172.7902,83.32,66,7,11.21,KI,2021-08-11 01:33:38,NaN,NaN
2,2,Ravenna,44.4167,11.9833,78.10,91,75,2.68,IT,2021-08-11 01:36:37,NaN,NaN
3,3,Shache,38.4167,77.2406,82.47,19,0,1.97,CN,2021-08-11 01:36:39,NaN,NaN
4,4,Hilo,19.7297,-155.0900,83.93,80,75,8.05,US,2021-08-11 01:33:41,NaN,NaN

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
clean_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
clean_df.head(10)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Description,Current Description
1,1,Butaritari,3.0707,172.7902,83.32,66,7,11.21,KI,2021-08-11 01:33:38,NaN,NaN
2,2,Ravenna,44.4167,11.9833,78.10,91,75,2.68,IT,2021-08-11 01:36:37,NaN,NaN
3,3,Shache,38.4167,77.2406,82.47,19,0,1.97,CN,2021-08-11 01:36:39,NaN,NaN
4,4,Hilo,19.7297,-155.0900,83.93,80,75,8.05,US,2021-08-11 01:33:41,NaN,NaN
9,9,Muroto,33.2833,134.1500,82.44,84,100,15.41,JP,2021-08-11 01:36:40,NaN,NaN
11,11,Padang,-0.9492,100.3543,77.05,70,99,4.34,ID,2021-08-11 01:36:14,NaN,NaN
12,12,Waddan,29.1614,16.1390,81.55,36,0,3.36,LY,2021-08-11 01:36:41,NaN,NaN
14,14,Phanom Sarakham,13.7479,101.3553,85.89,78,100,8.77,TH,2021-08-11 01:36:42,NaN,NaN
18,18,Kavieng,-2.5744,150.7967,86.41,60,6,8.12,PG,2021-08-11 01:36:43,NaN,NaN
22,22,Cabo San Lucas,22.8909,-109.9124,84.15,86,90,12.66,MX,2021-08-11 01:33:21,NaN,NaN

In [5]:
# 4a. Determine if there are any empty rows.
clean_df.count()

City_ID                1313
City                   1313
Lat                    1313
Lng                    1313
Max Temp               1313
Humidity               1313
Cloudiness             1313
Wind Speed             1313
Country                1313
Date                   1313
Description             787
Current Description     264
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df.dropna(how='all')

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Description,Current Description
1,1,Butaritari,3.0707,172.7902,83.32,66,7,11.21,KI,2021-08-11 01:33:38,NaN,NaN
2,2,Ravenna,44.4167,11.9833,78.10,91,75,2.68,IT,2021-08-11 01:36:37,NaN,NaN
3,3,Shache,38.4167,77.2406,82.47,19,0,1.97,CN,2021-08-11 01:36:39,NaN,NaN
4,4,Hilo,19.7297,-155.0900,83.93,80,75,8.05,US,2021-08-11 01:33:41,NaN,NaN
9,9,Muroto,33.2833,134.1500,82.44,84,100,15.41,JP,2021-08-11 01:36:40,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
3468,3468,Dzaoudzi,-12.7887,45.2699,75.09,83,75,10.36,YT,2021-08-12 03:39:05,NaN,broken clouds
3469,3469,Nizhniy Baskunchak,48.2198,46.8311,86.59,26,59,11.25,RU,2021-08-12 03:39:05,NaN,broken clouds
3477,3477,Manokwari,-0.8667,134.0833,83.41,70,96,7.31,ID,2021-08-12 03:37:31,NaN,overcast clouds
3478,3478,Along,28.1667,94.7667,77.32,99,100,1.86,IN,2021-08-12 03:39:07,NaN,overcast clouds
3484,3484,Suchiapa,16.6167,-93.0833,80.92,65,75,13.80,MX,2021-08-12 03:39:09,NaN,broken clouds

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Butaritari,KI,83.32,NaN,3.0707,172.7902,
2,Ravenna,IT,78.10,NaN,44.4167,11.9833,
3,Shache,CN,82.47,NaN,38.4167,77.2406,
4,Hilo,US,83.93,NaN,19.7297,-155.0900,
9,Muroto,JP,82.44,NaN,33.2833,134.1500,
11,Padang,ID,77.05,NaN,-0.9492,100.3543,
12,Waddan,LY,81.55,NaN,29.1614,16.1390,
14,Phanom Sarakham,TH,85.89,NaN,13.7479,101.3553,
18,Kavieng,PG,86.41,NaN,-2.5744,150.7967,
22,Cabo San Lucas,MX,84.15,NaN,22.8909,-109.9124,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.

params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

hotels
# 6b. Iterate through the hotel DataFrame.


    # 6c. Get latitude and longitude from DataFrame

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    

    # 6e. Make request and retrieve the JSON data from the search. 
   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.

{'html_attributions': [],
 'next_page_token': 'Aap_uEAA-9hDkubwnsDT-_8TuzPZUczm5Q6su-kpmtoL8_iWFnuvk3eOXJ1KQHf6ENuFn-H9MhJrHgLBGgYrxAztycekcq9-Mum0FgfTDVjVLhleFyjMZi_kq6Zq7V0V3qs6UEqhxseAryA1e1qOLY0fhSKWHUwH3m9pmIJ-685ggmUCCA3jDgfq7ZUKs4vK0bY_6hK4iJE93bwk-HC_MSJBvL4FLcmsg-WdUDiW0rTDfWOnS0RSw3YIdZq_AX-g_3ouujLaLXVslnCG96ml3T_ogEsDp4vnpwgiozdyycyaLakkDQS6LESUm7X1mQSDdaWk8Vm-vxfxoe52ZjRMcdp7nRK_mOuCB6MZeYOhGSQduMhLlaW7-pV54QAF3EFLC5djv306AiYZkIuFMRGgrkCH6mfQ9LBwYCkCcbCQi54oCvZQnGJgqRTI0y_5',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277},
    'viewport': {'northeast': {'lat': 48.8594393802915,
      'lng': 2.354352980291503},
     'southwest': {'lat': 48.8567414197085, 'lng': 2.351655019708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Duo',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">Hôtel Duo</a>'],
     'photo_reference': 'Aap_uEDpPSx--W_4RFdeuvvZIwbuI-NrWT6GmfSC9hWc-AA_fdv61BJuK5V0JrcEH57MplKEA83ZIjUughGdBMcTlWvWk-MZIao16YUviNl9BENoSj_SUSmWO4eRQH47eWrtRQC8PokyQcd2m3KSQiLg3w49cePlcHRQmA1h48tA49wAmmq_',
     'width': 5760}],
   'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'plus_code': {'compound_code': 'V953+65 Paris, France',
    'global_code': '8FW4V953+65'},
   'rating': 4.2,
   'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'scope': 'GOOGLE',
   'types': ['night_club',
    'spa',
    'lodging',
    'bar',
    'gym',
    'health',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 285,
   'vicinity': '11 Rue du Temple, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944},
    'viewport': {'northeast': {'lat': 48.8595495802915,
      'lng': 2.347780980291502},
     'southwest': {'lat': 48.8568516197085, 'lng': 2.345083019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Britannique - Paris Centre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1426,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">Hôtel Britannique - Paris Centre</a>'],
     'photo_reference': 'Aap_uEAtu5VVi1oC50H1CfgXMTbmD806z0oEvUZJi1s5PoP-hhs8U_pN5u6ehhG4T0JLlOStVlVY-fGT1rrdj52eP6d_iRUKYg45LEe1tsWh4HKTaef5pZomzK2S8-PFIcvGwykyWmGcT-M8wOP8uhUBgB95_cgioUPkgb_xikuF9SyeYRX-',
     'width': 1476}],
   'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'plus_code': {'compound_code': 'V85W+8H Paris, France',
    'global_code': '8FW4V85W+8H'},
   'rating': 4.6,
   'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 571,
   'vicinity': '20 Avenue Victoria, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8606655, 'lng': 2.3469293},
    'viewport': {'northeast': {'lat': 48.8617653302915,
      'lng': 2.348020880291502},
     'southwest': {'lat': 48.85906736970851, 'lng': 2.345322919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Les Halles Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 849,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Les Halles Paris (Apart hotel Paris)</a>'],
     'photo_reference': 'Aap_uEA5-Ld2KE4FTto4gzU5d4JPcxr404gBSA0mlrEvjU-vZ_duf1MVjaiHmFgPcV9kCJs3jmIqKIHAQDVsv4US6hIDQV4mIlY8xJj6pMIp55vO4QAeANsPf7RT3lW9OMWy3nr0Jjf7SYiM9YHyh_EBHb46VEFBkK6MWLNTdHJPQXAYcmSI',
     'width': 1280}],
   'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'plus_code': {'compound_code': 'V86W+7Q Paris, France',
    'global_code': '8FW4V86W+7Q'},
   'rating': 4.1,
   'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 831,
   'vicinity': '4 Rue des Innocents, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8607658, 'lng': 2.3465318},
    'viewport': {'northeast': {'lat': 48.86205553029149,
      'lng': 2.347674930291502},
     'southwest': {'lat': 48.85935756970849, 'lng': 2.344976969708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Novotel Paris Les Halles',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111815616573299411056">Novotel Paris Les Halles</a>'],
     'photo_reference': 'Aap_uECzAv942cnBN5nlTA7IXWtzYRMfWHGcr3IVocvb3eOeM8ZR00eZ1BTxhSs9EpLAo9EaWsKnpnkH8vRro-cYV6Rq5XSGbFOxZDEz5KNKHAlQs5zT8LC4GU-_eI2GjrT69YCqZoFBKQWI_48r5SuUFgUVu7mWudcjJzwQvObetTo0f_a9',
     'width': 3000}],
   'place_id': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'plus_code': {'compound_code': 'V86W+8J Paris, France',
    'global_code': '8FW4V86W+8J'},
   'rating': 4.4,
   'reference': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2186,
   'vicinity': '8 Place Marguerite de Navarre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86034799999999, 'lng': 2.344054},
    'viewport': {'northeast': {'lat': 48.8616503302915,
      'lng': 2.345521080291502},
     'southwest': {'lat': 48.8589523697085, 'lng': 2.342823119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Ducs de Bourgogne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1390,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101411638353598558320">Hôtel Ducs de Bourgogne</a>'],
     'photo_reference': 'Aap_uEDH2602tTMywe8yvWiixCBnVpf0GPYn1LBV96X1h8wPtM2-RfbZh1b2SLK3WCuWsFudLZj1pO423nWlzQLClzLQ1mbF1zvQwS_TYBATPgPVuXnvDk0zeXcazwtwF7X_LG74pIeerf0mh2pGmnLhQL7BV6jd37sXfLNsLElIOf2B9T5v',
     'width': 2048}],
   'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'plus_code': {'compound_code': 'V86V+4J Paris, France',
    'global_code': '8FW4V86V+4J'},
   'rating': 4.5,
   'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 277,
   'vicinity': '19 Rue du Pont Neuf, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8555091, 'lng': 2.3408736},
    'viewport': {'northeast': {'lat': 48.8569076302915,
      'lng': 2.342319280291502},
     'southwest': {'lat': 48.8542096697085, 'lng': 2.339621319708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Saint-Germain-des-Prés Paris (Apart hotel Paris)',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113188832595116816387">Citadines Saint-Germain-des-Prés Paris</a>'],
     'photo_reference': 'Aap_uEAt2eFVZiROEMs4mhuVZmLyReYxRBad2v3ajBdvMI0Ies94tIRVQay4hci981pYgwMwa2AIwgTwyLLQnQUQ3KnXGFMXowZbZUFC7a82pXi9EkWn5ruBgAPkMY5291b1ZLV4DeTt5jKmRJqcpR8eY_WKYG40rRlwrk2_uvu2ql8thz-A',
     'width': 6720}],
   'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'plus_code': {'compound_code': 'V84R+68 Paris, France',
    'global_code': '8FW4V84R+68'},
   'rating': 4.3,
   'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 687,
   'vicinity': '53 ter Quai des Grands Augustins, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8663516, 'lng': 2.360645700000001},
    'viewport': {'northeast': {'lat': 48.86775293029149,
      'lng': 2.361904930291503},
     'southwest': {'lat': 48.8650549697085, 'lng': 2.359206969708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Paris France Hôtel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2673,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102332962500946068613">Paris France Hôtel</a>'],
     'photo_reference': 'Aap_uECEeLu8S7E8o5oE5WgKzm9A1Nq9b0U0kcNFSZhOi-s5kHVxrG3M4_pSlK5ZuchC9tAd3mCT4UzDCTABiLkrMU-TOs-nt2AvJPmYqizAMTDSXVyxggByFfe0xcgOnpFKTfF-ZIwTowX5ciuVw9pGXf5dpKfZmenlk_ReWZ5D2aCv1H8M',
     'width': 3463}],
   'place_id': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'plus_code': {'compound_code': 'V986+G7 Paris, France',
    'global_code': '8FW4V986+G7'},
   'rating': 4.3,
   'reference': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 379,
   'vicinity': '72 Rue de Turbigo, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86386539999999, 'lng': 2.3325488},
    'viewport': {'northeast': {'lat': 48.8650759802915,
      'lng': 2.333775730291502},
     'southwest': {'lat': 48.8623780197085, 'lng': 2.331077769708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hotel Regina Louvre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3700,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109908333790946649027">Hôtel Regina Louvre</a>'],
     'photo_reference': 'Aap_uEBCR-g1a6yCuyAu7_rdKaqAHt9haiWxJ5Bjyo9CYEM1E_6BQ5S_nY1b04BGha_YDuNfx9PBXGPOdR9UuOcHcPg6ivaDWvvy5Kpnhu9Hhsr99KMDWoEHwF0zxqg8UI4XNSLLowK2l7WWzKAz7gUQ0ddTf0xgBmj-K5jFImMVT_-CGNfP',
     'width': 5550}],
   'place_id': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'plus_code': {'compound_code': 'V87M+G2 Paris, France',
    'global_code': '8FW4V87M+G2'},
   'rating': 4.5,
   'reference': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 500,
   'vicinity': '2 Place des Pyramides, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84795229999999, 'lng': 2.370869},
    'viewport': {'northeast': {'lat': 48.8492035302915,
      'lng': 2.372290080291501},
     'southwest': {'lat': 48.8465055697085, 'lng': 2.369592119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'ibis Paris Gare de Lyon Ledru Rollin 12ème',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110161480967920528437">stefan kebbekus</a>'],
     'photo_reference': 'Aap_uEAOF1YadFwg0bwi-5q3qcJf9MuD66ewDREIpgGWhQpusMItll5BWgK9D9iUcsTM62iNqGxaz2KTePwbvTTvWqAxYJiyRwlRQu7uFbDhJLwGgH31IZ-F5mfhHDhtSW_ori97g4-BDmu2FJQWo-plub-fM3G3Irg05oYihTCkzPhYSgzD',
     'width': 4000}],
   'place_id': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'plus_code': {'compound_code': 'R9XC+58 Paris, France',
    'global_code': '8FW4R9XC+58'},
   'rating': 4.1,
   'reference': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 805,
   'vicinity': '41/43 Avenue Ledru Rollin, Paris'},
  {'business_status': 'CLOSED_TEMPORARILY',
   'geometry': {'location': {'lat': 48.8710647, 'lng': 2.34991},
    'viewport': {'northeast': {'lat': 48.87241888029151,
      'lng': 2.351188530291502},
     'southwest': {'lat': 48.86972091970851, 'lng': 2.348490569708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel des Comédies Paris',
   'permanently_closed': True,
   'photos': [{'height': 4000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114696623290303183213">Noble</a>'],
     'photo_reference': 'Aap_uEDvY44woTt7wX2L_gF3gqpyDGPRG8jy9PqVgN05SVhhKWT6M693xCLbSBC1FpT6TOsZGszAaGPOAQoiyt4_B-fuqqFyiaEc2pTB4QyRx2t8iivEb1Sz46qUdm2GZP1M8dovThak_PhWmqGVYllHzHGHEcD4TK2_w9xuO5M1ZXQEtwNh',
     'width': 3000}],
   'place_id': 'ChIJn6ginxZu5kcRmAEK0OHm0cI',
   'plus_code': {'compound_code': 'V8CX+CX Paris, France',
    'global_code': '8FW4V8CX+CX'},
   'rating': 4.2,
   'reference': 'ChIJn6ginxZu5kcRmAEK0OHm0cI',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 194,
   'vicinity': "8 Rue d'Hauteville, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84754640000001, 'lng': 2.3718722},
    'viewport': {'northeast': {'lat': 48.8488750302915,
      'lng': 2.373125480291502},
     'southwest': {'lat': 48.8461770697085, 'lng': 2.370427519708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel De France Gare de Lyon Bastille',
   'photos': [{'height': 787,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117462031751048846575">Hôtel De France Gare de Lyon Bastille</a>'],
     'photo_reference': 'Aap_uEBjj0_toAUFOtYOcPylVSPmDVbqVRYG9kUBORwFGMXcP-oF2-Gb0K-YBBRuvdRpLzArbG1M7XIZfO5f5cS7dl-ZEToqqarJBiBpznhJA5Y9ZC2q3L2nCoVWdz-EtMopYQoABYsOMZFEYzksN8YssdMaBacysjVjPKDPB-n2NvkD2nqU',
     'width': 1181}],
   'place_id': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'plus_code': {'compound_code': 'R9XC+2P Paris, France',
    'global_code': '8FW4R9XC+2P'},
   'rating': 3.3,
   'reference': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 381,
   'vicinity': '12 Rue de Lyon, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8717386, 'lng': 2.3447052},
    'viewport': {'northeast': {'lat': 48.8731394302915,
      'lng': 2.346067130291502},
     'southwest': {'lat': 48.8704414697085, 'lng': 2.343369169708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Prélude Opéra Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 5120,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113098608949799179620">Chrystelle Baudry</a>'],
     'photo_reference': 'Aap_uEDUq2AL83-WtRatHGTfw3W898dukW_7GT3YIAsju07l5UQOS6deSYPnzpWH-bCWtnvtgg1io_iQBymcN2tJ-APOmc67bVIUKdI-1ArlxJRq-zQhE4rBxl8BJ6TP_Pr1XJXEGbIV1Uk-Tb9WKxkfSo5dlmCPuja4cfDcoNYT9gy8y5a5',
     'width': 3840}],
   'place_id': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'plus_code': {'compound_code': 'V8CV+MV Paris, France',
    'global_code': '8FW4V8CV+MV'},
   'rating': 4.1,
   'reference': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 363,
   'vicinity': '8 Cité Bergère, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8423491, 'lng': 2.3632246},
    'viewport': {'northeast': {'lat': 48.84365908029149,
      'lng': 2.364711430291502},
     'southwest': {'lat': 48.8409611197085, 'lng': 2.362013469708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Libertel Austerlitz Jardin des Plantes',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114802271282641766772">Hôtel Libertel Austerlitz Jardin des Plantes</a>'],
     'photo_reference': 'Aap_uED7Qf8vu1FKu3VHW4HN1BVGELnrsTCyWRxbZ8lZ5ZLol0Pk_LOjuM31iu7fWf9DkYqLg-CAu8M82ekcIVHYdEAGa6x7V-guuZzl0SlQBO0jp4j-5dLmEyIKBWth6nA_vmK3RvR-urmXVi6vRDUBzTtJYJ6F7I9MNCd2MjwdBaWPFYeR',
     'width': 6720}],
   'place_id': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'plus_code': {'compound_code': 'R9R7+W7 Paris, France',
    'global_code': '8FW4R9R7+W7'},
   'rating': 4,
   'reference': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 433,
   'vicinity': "12 Boulevard de l'Hôpital, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.864294, 'lng': 2.3307997},
    'viewport': {'northeast': {'lat': 48.8655772302915,
      'lng': 2.332153880291502},
     'southwest': {'lat': 48.8628792697085, 'lng': 2.329455919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Saint James Albany Paris Hôtel Spa',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 400,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108570400659068256718">Saint James Albany Paris Hôtel Spa</a>'],
     'photo_reference': 'Aap_uEASgEHiHUYtlsTTg0hyNihmvr2L00xUOvYA0Vn4xD2s37rOCELv5GiEFWTvLCd38_5uUCMEa6z2imUC1_0w3WmkJAtI5HIKj82w2BjpcUzquzQlIxRT219auZp2KU__hNQQMiPCeQiWXI7Kz-szmv7KeP8d7XekgOwEdur7UCaUJlcX',
     'width': 600}],
   'place_id': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'plus_code': {'compound_code': 'V87J+P8 Paris, France',
    'global_code': '8FW4V87J+P8'},
   'rating': 4,
   'reference': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 1074,
   'vicinity': '202 Rue de Rivoli, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.87110329999999, 'lng': 2.3389728},
    'viewport': {'northeast': {'lat': 48.8724588802915,
      'lng': 2.340112930291502},
     'southwest': {'lat': 48.8697609197085, 'lng': 2.337414969708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Icône',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1066,

In [9]:
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [15]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.head(10)
clean_hotel_df=hotel_df.dropna()
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2789,Butaritari,KI,83.37,clear sky,3.0707,172.7902,Isles Sunset Lodge
2790,Ravenna,IT,77.22,clear sky,44.4167,11.9833,Hotel Tatì
2791,Shache,CN,87.42,broken clouds,38.4167,77.2406,Delong Hotel
2792,Hilo,US,80.33,overcast clouds,19.7297,-155.0900,Hilo Hawaiian Hotel
2797,Muroto,JP,77.04,moderate rain,33.2833,134.1500,Oota Ryokan
2799,Padang,ID,84.25,overcast clouds,-0.9492,100.3543,Mercure Padang
2800,Waddan,LY,82.08,clear sky,29.1614,16.1390,محل الشريف محمد العايب
2802,Phanom Sarakham,TH,85.89,broken clouds,13.7479,101.3553,SC Resort
2806,Kavieng,PG,83.77,light rain,-2.5744,150.7967,Nusa Island Retreat
2808,Pueblo,US,88.38,clear sky,38.2545,-104.6091,Courtyard by Marriott Pueblo Downtown

In [16]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [17]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template ="""
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]
print(locations)

          Lat       Lng
2789   3.0707  172.7902
2790  44.4167   11.9833
2791  38.4167   77.2406
2792  19.7297 -155.0900
2797  33.2833  134.1500
...       ...       ...
3468 -12.7887   45.2699
3469  48.2198   46.8311
3477  -0.8667  134.0833
3478  28.1667   94.7667
3484  16.6167  -93.0833

[264 rows x 2 columns]

In [18]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# 11b. Display the figure
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
#heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
           #  max_intensity=300, point_radius=4)
#marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
#fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))